:: SPDX-FileCopyrightText: 2018 Christian Sailer
::
:: SPDX-License-Identifier: GPL-3.0-or-later
::
:: REUSE-IgnoreStart

@echo off
del version_defs.h
echo // SPDX-FileCopyrightText: 2018 Christian Sailer >> version_defs.h

echo // SPDX-License-Identifier: GPL-3.0-or-later >> version_defs.h
echo. >> version_defs.h
echo // This file is autogenerated - do not modify it directly! >> version_defs.h
echo. >> version_defs.h
echo #pragma once >> version_defs.h
echo. >> version_defs.h

:: Get date in correct form (YYYY/MM/DD).
for /f "skip=1" %%x in ('wmic os get localdatetime') do if not defined MyDate set MyDate=%%x
for /f %%x in ('wmic path win32_localtime get /format:list ^| findstr "="') do set %%x
set fmonth=00%Month%
set fday=00%Day%
set today=%Year%/%fmonth:~-2%/%fday:~-2%

echo #ifndef APP_DATE >> version_defs.h
echo #define APP_DATE "%today%" >> version_defs.h
echo #endif >> version_defs.h
echo. >> version_defs.h
for /f "delims=" %%A in ('git rev-parse --abbrev-ref HEAD') do set "mybranch=%%A"
echo #ifndef APP_GIT_BRANCH >> version_defs.h
echo #define APP_GIT_BRANCH "%mybranch%" >> version_defs.h
echo #endif >> version_defs.h
echo. >> version_defs.h
for /f "delims=" %%A in ('git log "--pretty=format:%%h" -n 1') do set "mycommit=%%A"
echo #ifndef APP_GIT_COMMIT >> version_defs.h
echo #define APP_GIT_COMMIT "%mycommit%" >> version_defs.h
echo #endif >> version_defs.h
